import { useMemo } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { AppLayout } from '@/components/layout/AppLayout'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { patients } from '@/data/patients'
import { computeTriageForPatient } from '@/lib/triage'
import { buildPatientIntelligence } from '@/data/patientIntelligence'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <Card>
      <h2 className="text-sm font-semibold uppercase tracking-wide text-text-muted">{title}</h2>
      <div className="mt-3 text-sm text-text">{children}</div>
    </Card>
  )
}

const triageCardStyle = {
  Green: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  Yellow: 'bg-amber-50 text-amber-700 border-amber-200',
  Red: 'bg-red-50 text-red-700 border-red-200',
  Black: 'bg-slate-200 text-slate-800 border-slate-300',
} as const

export function PatientIntelligencePage() {
  const { patientId } = useParams()
  const navigate = useNavigate()

  const patient = useMemo(() => patients.find((entry) => entry.id === patientId), [patientId])
  const triage = useMemo(() => (patient ? computeTriageForPatient(patient) : null), [patient])

  if (!patient || !triage) {
    return (
      <AppLayout>
        <div className="rounded-2xl bg-white p-5 text-sm text-text-muted shadow-sm">Patient not found.</div>
      </AppLayout>
    )
  }

  const intelligence = buildPatientIntelligence(patient, triage.level)
  const triageClassName = triageCardStyle[intelligence.triage.display]

  return (
    <AppLayout>
      <div className="mx-auto flex w-full max-w-5xl flex-col gap-4 pb-6">
        <header className="rounded-2xl bg-white p-4 shadow-sm">
          <div className="flex items-start justify-between gap-3">
            <div>
              <h1 className="text-xl font-semibold text-text">{patient.name}</h1>
              <p className="mt-1 text-sm text-text-muted">
                {patient.age} / {patient.gender}
              </p>
              <p className="mt-1 text-sm text-text-muted">Hospital ID: {patient.id}</p>
              <p className="mt-1 text-sm text-text-muted">Hospital: City General Hospital</p>
            </div>
            <div className="text-right text-sm text-text-muted">
              <p>Date & Time: {new Date().toLocaleString('en-IN')}</p>
              <p className="mt-1">Updated: {intelligence.updatedLabel}</p>
              <p className="mt-1 text-primary-700">Generated by Klinimate AI</p>
            </div>
          </div>
        </header>

        <Section title="AI Clinical Summary">
          <p className="leading-6">{intelligence.clinicalSummary}</p>
        </Section>

        <Card className="p-5">
          <h2 className="text-sm font-semibold uppercase tracking-wide text-text-muted">Triage Status</h2>
          <div className={`mt-3 rounded-2xl border px-4 py-4 ${triageClassName}`}>
            <p className="text-2xl font-bold">
              {intelligence.triage.emoji} {intelligence.triage.display.toUpperCase()}
            </p>
            <p className="mt-1 text-sm font-semibold">{intelligence.triage.urgencyLabel}</p>
            <p className="mt-2 text-sm">Recommended Review: {intelligence.triage.recommendedReview}</p>
          </div>
        </Card>

        <Section title="Clinical Reasoning">
          <div className="mb-2 inline-flex rounded-full bg-primary-50 px-3 py-1 text-xs font-semibold text-primary-700">
            Generated by Klinimate AI
          </div>
          <div className="space-y-3">
            <div>
              <p className="font-semibold text-text">Key Clinical Findings</p>
              <ul className="mt-2 list-disc space-y-1 pl-5 text-text-muted">
                {intelligence.redFlagFindings.map((finding) => (
                  <li key={finding}>{finding}</li>
                ))}
              </ul>
            </div>
            <div>
              <p className="font-semibold text-text">AI Clinical Interpretation</p>
              <p className="mt-2 text-text-muted">
                The combination of hypoxemia, tachypnea, tachycardia and persistent fever suggests
                evolving respiratory infection requiring urgent review and close monitoring.
              </p>
            </div>
          </div>
        </Section>

        <Section title="Top Probable Diagnoses">
          <ul className="space-y-2">
            {intelligence.probableDiagnoses.map((diagnosis, index) => (
              <li key={diagnosis} className="flex items-center justify-between rounded-xl bg-surface-muted px-3 py-2">
                <span>{diagnosis}</span>
                <span className="text-xs font-semibold text-primary-700">#{index + 1}</span>
              </li>
            ))}
          </ul>
        </Section>

        <Section title="Differential Diagnoses">
          <ul className="list-disc space-y-1 pl-5 text-text-muted">
            {intelligence.differentialDiagnoses.map((diagnosis) => (
              <li key={diagnosis}>{diagnosis}</li>
            ))}
          </ul>
        </Section>

        <Section title="Red Flag Findings">
          <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
            {intelligence.redFlagFindings.map((flag) => (
              <div key={flag} className="rounded-xl bg-rose-50 px-3 py-2 text-sm text-rose-700">
                {flag}
              </div>
            ))}
          </div>
        </Section>

        <Section title="Recommended Investigations">
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            <div>
              <p className="font-semibold text-text">Urgent</p>
              <ul className="mt-2 list-disc space-y-1 pl-5 text-text-muted">
                {intelligence.investigations.urgent.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </div>
            <div>
              <p className="font-semibold text-text">Routine</p>
              <ul className="mt-2 list-disc space-y-1 pl-5 text-text-muted">
                {intelligence.investigations.routine.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </div>
          </div>
        </Section>

        <Section title="Initial Management Plan">
          <ul className="space-y-2">
            {intelligence.initialManagementPlan.map((plan) => (
              <li key={plan} className="rounded-xl bg-surface-muted px-3 py-2 text-text">
                <span className="mr-2 text-primary-700">☑</span>
                {plan}
              </li>
            ))}
          </ul>
        </Section>

        <Section title="Specialist Recommendation">
          <p className="font-semibold text-text">{intelligence.specialistRecommendation.specialty}</p>
          <p className="mt-2 text-text-muted">{intelligence.specialistRecommendation.reason}</p>
        </Section>

        <Card>
          <details>
            <summary className="cursor-pointer text-sm font-semibold uppercase tracking-wide text-text-muted">
              Why These Diagnoses?
            </summary>
            <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-text-muted">
              {intelligence.whyTheseDiagnoses.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </details>
        </Card>

        <Section title="Next Recommended Actions">
          <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
            {intelligence.nextActions.map((action) => (
              <div key={action} className="rounded-xl border border-border bg-white px-3 py-2 text-sm font-medium text-text">
                {action}
              </div>
            ))}
          </div>
        </Section>

        <Card>
          <p className="text-sm text-text-muted">
            Klinimate AI provides Clinical Decision Support only.
          </p>
          <p className="mt-1 text-sm text-text-muted">
            Final diagnosis, investigations and treatment decisions remain the responsibility of the treating clinician.
          </p>
        </Card>

        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
          <Button size="lg" fullWidth>
            Send to Klinimate Intensivist
          </Button>
          <Button variant="secondary" size="lg" fullWidth>
            Request Specialist Opinion
          </Button>
          <Button variant="secondary" size="lg" fullWidth onClick={() => navigate(`/patients/${patient.id}/dashboard`)}>
            Edit Patient
          </Button>
          <Button variant="ghost" size="lg" fullWidth>
            Save Draft
          </Button>
          <Button variant="ghost" size="lg" fullWidth>
            Download Clinical Summary
          </Button>
          <Button variant="ghost" size="lg" fullWidth>
            Print Report
          </Button>
        </div>
      </div>
    </AppLayout>
  )
}
